# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '56885aa9-01a9-4b8e-84e7-f5d2cde4fe29'
  imageRepository: 'marcelgoltdcsplab'
  containerRegistry: 'tdcsp2020cr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Temperature.Converter.API/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '.'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '.'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: './Temperature.Converter.API'
        arguments: '-o ./Temperature.Converter.API/out'
        zipAfterPublish: false
        modifyOutputPath: false

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Visual Studio Professional(94211381-cbc5-4473-b790-de89414c0bfc)'
        appType: 'webAppContainer'
        WebAppName: 'tdcsp2020-lab-dockerapp'
        DockerNamespace: '$(containerRegistry)'
        DockerRepository: '$(imageRepository)'
        DockerImageTag: '$(tag)'
